# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 with Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set JAVA_HOME for Gradle
        run: echo "export GRADLE_OPTS='-Dorg.gradle.java.home=${JAVA_HOME}'" >> $GITHUB_ENV

      - name: Print Current Directory
        run: |
          pwd
          ls
          
      # - name: Build with Gradle
      #   run: |
      #     cd paypro-android-backend
      #     ls
      #     chmod +x gradlew
      #     ./gradlew build
      - name: Deploy to VPS
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H 158.220.113.254 >> $HOME/.ssh/known_hosts

          ssh -i $HOME/.ssh/id_rsa root@158.220.113.254 "\
          cd baze-projekt && \
          mkdir -p kafka-data-streaming && \
          cd kafka-data-streaming && \
          git init && \
          git remote add origin https://github.com/timjuic/kafka-iot-data-streaming.git && \
          git fetch && \
          git pull origin main && \
          ls && \
          pwd && \
          chmod +x ./gradlew && \
          ./gradlew build && \
          ./gradlew run"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

